.\" This description page for des
.TH des "1" "2022-04-16" "des 02.02" "User Commands"
.SH NAME
des

.SH DESCRIPTION
This is the man documentation of des.

.SH SYNOPSIS
.B des [--help | -h] - Help
.br
.B des --version - Return des version
.br
.B des [--verbose | -v] - Enable verbose
.br
.B des [--text | -txt] - Define text the unencrypted input/ output (up to 16MB)
.br
.B des --file-input=... --file-output=... - Work with files
.br
.B des [--decrypt | -d] - Decrypt, otherwise encrypt
.br
.B des [--new-key | -nk | --generate-key | -gk] - Request a new key
.br
.B des --key=... - Get the key
.br
.B des --message=... - Get the message (base64 encoded by default)

.SH AUTHORS
Castellani Davide (@DavideC03): owner
