.\" This description page for des
.TH des "1" "2022-03-12" "des 00.01" "User Commands"
.SH NAME
des
.SH SYNOPSIS
.B des - launch application
.br
.B des [--help | -h] - Help
.br
.B des [--login | -l] - Login with help
.br
.B des [--login | -l] [--username | -u] [--token | -t] - Login without any input request
.SH DESCRIPTION
Repo containing the clientside for Ubuntu/Debian
.SH AUTHORS
Castellani Davide (@DavideC03): owner