name: Upgrade documentation (Wiki + README.md)
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'releases/*'

jobs:
  upgrade-documentation:
    runs-on: ubuntu-latest
    environment:
      name: documentation
    steps:
    - name: Initial setup
      run: |
        sudo apt update -y
        sudo pip install BeautifulSoup4
        {
          git clone --recurse-submodules --depth 1 https://$.GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.wiki.git wiki
        } || {
          mkdir wiki
        }
        git clone --recurse-submodules --depth 1 https://$.GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git -b $(echo ${GITHUB_REF#refs/heads/}) repo
        rm -f wiki/*.md
    - name: Home file
      run: |
        cd wiki
        python3 << EOF
        import requests
        import json
        from bs4 import BeautifulSoup
        def web_request(url):
          """ Make a web request and return the response
          """ 
          return requests.get(url, auth=("$GITHUB_ACTOR", "${{ secrets.GITHUB_TOKEN }}")).text
        def get_json():
          """ Returns the json with description
          """
          return json.loads(web_request("$GITHUB_API_URL/repos/$GITHUB_REPOSITORY"))
        def get_social_img():
          """ Get social image
          """
          try:
            soup = BeautifulSoup(web_request("$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"), 'html.parser')
            return soup.find("meta", property="og:image")["content"]
          except:
            print("Error getting social image")
            return ""
        def get_content():
          """ Returns the file content
          """
          social_img = get_social_img()
          file_content = "## :octocat: Description :octocat:\n"
          file_content += get_json()["description"].replace(". ", ".\n\n").replace("wiki", "[wiki]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/wiki)") + "\n"
          file_content += f"![$GITHUB_REPOSITORY]({social_img})\n"
          return file_content
        if __name__ == "__main__":
          open("Home.md", "w+").write(str(get_content()))                    
        EOF
    - name: CHANGELOG file
      run: |
        cp repo/debian/changelog wiki/
        cd wiki
        sed -i 's/Changelog/:octocat: Changelog :octocat:/g' changelog
        sed -i 's/# /## /g' changelog
    - name: Directory structure file
      run: |
        cd wiki
        sudo apt install tree -y
        echo "## :octocat: Directory structure :octocat:" > Directory-Structure.md
        echo "" >> Directory-Structure.md
        echo "\`\`\`" >> Directory-Structure.md
        tree ../repo >> Directory-Structure.md
        echo "\`\`\`" >> Directory-Structure.md
        sed -i 's/├── debian/├── debian # debian control code/g' Directory-Structure.md
        sed -i 's/bin/bin # source code/g' Directory-Structure.md
        sed -i 's/docs/docs # documentation/g' Directory-Structure.md
    - name: _Footer file
      run: |
        cd wiki
        echo "---" > _Footer.md
        echo "Made w/ :heart: by Castellani Davide" >> _Footer.md
        echo "" >> _Footer.md
        echo "If you want to contribute you can start with:" >> _Footer.md
        echo "- [Discussion]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/discussions)" >> _Footer.md
        echo "- [Issue]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/issues/new)" >> _Footer.md
    - name: _Header file
      run: |
        cd wiki
        echo "# des" > _Header.md
        echo "[![GitHub license](https://img.shields.io/badge/license-GNU-green?style=flat)]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/blob/$(echo ${GITHUB_REF#refs/heads/})/docs/LICENSE)" >> _Header.md
        echo "![Author](https://img.shields.io/badge/author-Castellani%20Davide-green?style=flat)" >> _Header.md
        echo "![sys.platform supported](https://img.shields.io/badge/OS%20platform%20supported-all-blue?style=flat) " >> _Header.md
        echo "" >> _Header.md
    - name: Recreate README.md
      run: |
        cat wiki/_Header.md > repo/docs/README.md
        cat wiki/Home.md >> repo/docs/README.md
        cat wiki/Directory-Structure.md >> repo/docs/README.md
        echo "# Changelog" >> repo/docs/README.md
        cat wiki/changelog >> repo/docs/README.md
        echo "" >> repo/docs/README.md
        cat wiki/_Footer.md >> repo/docs/README.md
        sed -i 's/:octocat://g' repo/docs/README.md
    - name: git add & commit & upload wiki
      continue-on-error: true
      run: |
        {
          ls wiki/.git/ > /dev/null
        } && {
          cd wiki
          git config user.name "$GITHUB_ACTOR"
          git config user.email "help@castellanidavide.it"
          git add *
          git commit -m "Upgrade by automatic action"
          git push https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.wiki.git
        }
    - name: git add & commit & upload repo
      continue-on-error: true
      run: |
        cd repo
        git config user.name "$GITHUB_ACTOR"
        git config user.email "help@castellanidavide.it"
        git add *
        git commit -m "Upgrade by automatic action"
        git push https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git
